module.exports = {
    mobile: [
        { id: 'overview', label: 'Overview', type: 'doc' },
        {
            'Mobile UI': [
                {
                    type: 'autogenerated',
                    dirName: 'mobile-ui',
                }
            ]
        },
        {
            'Android SDK': [
                {
                    type: 'autogenerated',
                    dirName: 'android-sdk'
                }
            ]
        }
    ],
}
