module.exports = {
    mobile: [
        { id: 'mobile/overview', label: 'Overview', type: 'doc' },
        {
            'Mobile UI': [
                {
                    type: 'autogenerated',
                    dirName: 'mobile/mobile-ui',
                },
            ],
        },
        {
            'Android SDK': [
                {
                    type: 'autogenerated',
                    dirName: 'mobile/android-sdk'
                },
            ],
        },
    ],
}
