const sidebarMobile = require('./sidebarsMobile.js')

module.exports = {
    docs: [
        {
            type: 'html',
            value: '<strong>Guides & Tutorials</strong>',
            defaultStyle: true,
        },

        'guides-overview',

        {
            type: 'html',
            value: '<strong>Getting started</strong>',
            defaultStyle: true,
        },

        'quickstart',
        'tutorials/setup-env',
        'quickstart/quickstart-web',
        'quickstart/quickstart-android',
        'tutorials/dhis2-docker',
        {
            type: 'html',
            value: '<strong>Web Development</strong>',
            defaultStyle: true,
        },
        'tutorials/ui-library',
        {
            label: 'Plugins',
            type: 'category',
            collapsed: true,
            collapsible: true,
            link: {
                type: 'doc',
                id: 'plugins/general-plugin-guide',
            },
            items: [
                'plugins/general-plugin-guide',
                {
                    label: 'Capture Plugins',
                    type: 'category',
                    collapsed: true,
                    collapsible: true,
                    link: {
                        type: 'doc',
                        id: 'capture-plugins/developer/getting-started',
                    },
                    items: [
                        'capture-plugins/developer/getting-started',
                        'capture-plugins/developer/develop-a-capture-plugin',
                        'capture-plugins/developer/configure-a-capture-plugin',
                        {
                            'Form Field Plugin': [
                                'capture-plugins/developer/form-field-plugins/introduction',
                                'capture-plugins/developer/form-field-plugins/developer-details',
                                'capture-plugins/developer/form-field-plugins/manual-setup',
                            ],
                            'Enrollment Plugin': [
                                'capture-plugins/developer/enrollment-plugins/introduction',
                                'capture-plugins/developer/enrollment-plugins/developer-details',
                                'capture-plugins/developer/enrollment-plugins/manual-setup',
                            ],
                            'Bulk data entry Plugin': [
                                'capture-plugins/developer/bulk-data-entry-plugin/introduction',
                                'capture-plugins/developer/bulk-data-entry-plugin/developer-details',
                                'capture-plugins/developer/bulk-data-entry-plugin/manual-setup',
                            ],
                        },
                    ],
                },
                {
                    label: 'Dashboard Plugins',
                    type: 'category',
                    collapsed: true,
                    collapsible: true,
                    link: {
                        type: 'doc',
                        id: 'dashboard-plugins/developer/getting-started',
                    },
                    items: [
                        'dashboard-plugins/developer/getting-started',
                        'dashboard-plugins/developer/implement-a-dashboard-plugin',
                    ],
                },
            ],
        },
        {
            Guides: [
                'guides',
                {
                    'Local Development': [
                        'guides/spin-up-local-instance',
                        'guides/code-style',
                        'guides/debug-instance',
                    ],
                },
                {
                    label: 'Web UI Component Recipes',
                    type: 'category',
                    collapsed: true,
                    link: {
                        type: 'generated-index',
                        title: 'Web UI Components Recipes',
                        slug: 'ui/recipes',
                    },
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'ui/recipes',
                        },
                    ],
                },
                {
                    'DHIS2 App Runtime': [
                        'tutorials/app-runtime-query',
                        'tutorials/app-runtime-dynamic-query',
                        'tutorials/app-runtime-mutation',
                        'guides/query-playground',
                        'app-runtime/guides/display-alerts',
                        'app-runtime/guides/using-dataquery',
                    ],
                    'App Hub': [
                        'guides/submit-apphub',
                        'guides/apphub-guidelines',
                        'guides/publish-apphub',
                        'guides/setup-changelog'
                    ],
                    Translation: ['guides/translation-support'],
                },
            ],
        },
        {
            type: 'html',
            value: '<strong>Mobile Development</strong>',
            defaultStyle: true,
        },
        sidebarMobile.mobile,
        {
            type: 'html',
            value: '<strong>Integration</strong>',
            defaultStyle: true,
        },

        'integration/overview',
        'integration/dhis2-java-sdk',
        'integration/dhis2-python-client',
        'integration/apache-camel',
        'integration/camel-dhis2-component',
        {
            type: 'html',
            value: '<strong>General Guides</strong>',
            defaultStyle: true,
        },
        'dev-videos',
        {
            Conceptual: [
                'conceptual',
                'conceptual/git-workflow',
                'conceptual/jira-workflow',
            ],
        },
    ],
}
